name: Show Xcode version
on:
  workflow_dispatch:

jobs:
  show_xcode_version:
    runs-on: macos-latest
    steps:
    - name: Grep Xcode
      run: ls /Applications/ | grep Xcode
    - name: Select Xcode 11.7
      run: sudo xcode-select -s /Applications/Xcode_11.7.app/Contents/Developer
